// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeTips.Data;

#nullable disable

namespace SafeTips.Migrations
{
    [DbContext(typeof(SafeTipsContext))]
    [Migration("20260914210202_SeedHousekeepers")]
    partial class SeedHousekeepers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SafeTips.Models.Housekeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hotel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("profImg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Housekeepers");

                    b.HasData(
                        new
                        {
                            Id = 19863245,
                            Description = "Has worked here for 5 years",
                            Hotel = "Grand Village",
                            Name = "Marcyne",
                            profImg = ""
                        },
                        new
                        {
                            Id = 97393749,
                            Description = "Has worked here for 7 months",
                            Hotel = "Bonneville Mount",
                            Name = "Garry",
                            profImg = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
